version: '3'

services:

  task_webapp:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    container_name: taskContainer
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    environment:
      IN_DOCKER: 1
    ports:
      - "8000:8000"